meta_product_name: "Way to zero"
meta_title: "Way to zero - the #1 app that takes you to zero waste"
meta_description: "Embark with us on the zero waste journey. Face daily challenges and earn xp to become a SuperZero!"
meta_image: "cover.png" # should exist in `app/assets/images/`
